CREATE TABLE "Usuário" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "idade" varchar,
  "email" varchar UNIQUE
);

CREATE TABLE "Tarefas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "título" varchar,
  "nota" text,
  "data_de_criação" datetime,
  "prazo_de_conclusão" datetime,
  "concluído" boolean,
  "id_Usuário" int,
  "id_Categoria" int,
  "id_Prioridade" int
);

CREATE TABLE "Categoria" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "descrição" text,
  "id_Usuário" int
);

CREATE TABLE "Prioridade" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nível" varchar,
  "cor" varchar
);

COMMENT ON COLUMN "Tarefas"."nota" IS 'descrição da tarefa em específico';

ALTER TABLE "Tarefas" ADD FOREIGN KEY ("id_Usuário") REFERENCES "Usuário" ("id");

ALTER TABLE "Tarefas" ADD FOREIGN KEY ("id_Categoria") REFERENCES "Categoria" ("id");

ALTER TABLE "Tarefas" ADD FOREIGN KEY ("id_Prioridade") REFERENCES "Prioridade" ("id");

ALTER TABLE "Categoria" ADD FOREIGN KEY ("id_Usuário") REFERENCES "Usuário" ("id");
